// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VsProj.Persistence;

#nullable disable

namespace VsProj.Migrations
{
    [DbContext(typeof(VsDbContext))]
    [Migration("20221219132313_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VsProj.Models.PartnerInfo", b =>
                {
                    b.Property<int>("PARTNERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PARTNERID"), 1L, 1);

                    b.Property<int>("IRANYITOSZAM")
                        .HasColumnType("int");

                    b.Property<string>("PARTNERNEV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ROGZIDO")
                        .HasColumnType("datetime2");

                    b.Property<string>("UTCA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAROS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PARTNERID");

                    b.ToTable("PartnerInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
